Added login for assessment takers.
std702-itpm/itPolicyManager-app-react pull request #20
Opened 2020-07-07 05:21 UTC by ppuarat

2020-07-07 05:21 UTC, ppuarat commented
![image](https://user-images.githubusercontent.com/11331329/86717491-54d2da80-c076-11ea-91dc-8e4fe0dff4bf.png)

2020-07-08 00:03 UTC, ppuarat commented on src/views/dashboardUserSubPage/SubscribedPolicies.jsx
> +              }
https://reactjs.org/docs/conditional-rendering.html#inline-if-with-logical--operator

2020-07-08 02:29 UTC, AntonRozhanskii requested changes

2020-07-08 02:29 UTC, AntonRozhanskii commented on src/views/dashboardAccountablePersonSubPage/Assessment.jsx
> +        console.log(response.data);
```suggestion
```

2020-07-08 02:29 UTC, AntonRozhanskii commented on src/views/dashboardAccountablePersonSubPage/Assessment.jsx
> +
```suggestion
```

2020-07-08 02:29 UTC, AntonRozhanskii commented on src/views/dashboardAccountablePersonSubPage/Assessment.jsx
```suggestion
```

2020-07-08 02:29 UTC, AntonRozhanskii commented on src/views/dashboardAccountablePersonSubPage/Assessment.jsx
>    componentDidUpdate() {
```suggestion
```

2020-07-08 02:29 UTC, AntonRozhanskii commented on src/views/dashboardAccountablePersonSubPage/Assessment.jsx
> +      console.log(option);
```suggestion
```

2020-07-08 02:30 UTC, AntonRozhanskii approved these changes

2020-07-08 02:30 UTC, merged