Integrate React Quill
std702-itpm/itPolicyManager-app-react pull request #23
Opened 2020-07-14 12:09 UTC by AntonRozhanskii

This has been made to allow policy content formatting,
such as headings, lists, etc.

2020-07-14 12:20 UTC, AntonRozhanskii commented
Note, that within [src/components/PolicyViewer/PolicyViewer.js](https://github.com/std702-itpm/itPolicyManager-app-react/pull/23/files#diff-7db9ddb92f5401368799a2fae6987208) are mostly formatting.
The meaningful changes in this file are <PolicyEditor/> addition, and content changes handling function.

2020-07-14 12:25 UTC, AntonRozhanskii reviewed
Forgot to remove dubugging code)

2020-07-14 12:25 UTC, AntonRozhanskii commented on src/views/commonPage/DisplayPolicy.jsx
> +                console.log(response)
```suggestion
```

2020-07-15 00:38 UTC, ppuarat requested changes

2020-07-15 00:38 UTC, ppuarat commented on src/views/commonPage/printPreview.jsx
> +                        <p>Accountable Person: Kristof C (hardcoded) </p>
```suggestion
                        <p>Accountable Person: Kristof C</p>
```

2020-07-15 00:39 UTC, ppuarat approved these changes

2020-07-15 00:40 UTC, merged